### ISSUE TITLE
Pending request

### ISSUE THREAD

**Issue by LarsTi** [WISEA12/frontend#10]
Pending requests in docent are related to a 'orderBy=name' fixed the problem in backend (will end up in an error) but should also be fixed in frontend.

**Comment by fischermax** [comment]
changed it to 'orderBy=lastName'
But there is still a pending request because of the missing limit compare:
Request URL:http://localhost:8080/api/docent?orderBy=lastName&skip=10 (this one is pending)
Request URL:http://localhost:8080/api/docent?limit=10&orderBy=lastName&skip=0 (this on is state 200)

**Comment by LarsTi** [comment]
fixed it(possibly) in backend. please pull

**Comment by fischermax** [comment]
fixed; great Lars :-)
